//! User host-label validation, matching the agent's own label rules.
//!
//! The agent sanitizes label keys and values on arrival
//! (netdata/netdata @ c23face0bd94
//! `src/libnetdata/sanitizers/sanitizers-labels.c`: a key containing `:`
//! becomes `_`, a value containing `;` becomes `:`, and so on). Accepting a
//! key the agent will silently mutate means `environment.yaml` and the node's
//! live label set disagree — a drift an SRE finds in the node-info panel, not
//! us. So authoring surfaces refuse anything that would not survive the
//! round trip unchanged, using the agent's own table as the source of truth.
//!
//! Two more namespaces are closed to users here:
//!
//! * `_`-prefixed keys — the agent's automatic labels (`_os_name`, ...).
//! * This project's structural labels (`simulated`, `infra_sim_name`,
//!   `infra_sim_role`, `infra_sim_env`, site coordinates, device identity) —
//!   they carry load the runtime depends on (room rules, map placement) and
//!   are managed by the generator, not typed in.
//!
//! Credential-looking key names are refused outright: a label is public
//! metadata that lands in Cloud, and `api_key=...` in a host label is the
//! kind of mistake better prevented than audited.

use std::collections::BTreeMap;

/// Key length cap. The agent truncates beyond this; a key that would be
/// truncated is refused instead so what is authored is what ships.
pub const MAX_KEY_LEN: usize = 200;

/// Value caps: 200 UTF-8 characters and 800 bytes, whichever is smaller
/// (netdata/netdata @ c23face0bd94 `src/database/rrdlabels.h:23-24`).
pub const MAX_VALUE_CHARS: usize = 200;
pub const MAX_VALUE_BYTES: usize = 800;

/// The user-facing label whose value tiers the fleet: when set, the renderer
/// mirrors it into the generated `infra_sim_env` label so our own tag agrees
/// with the user's. `infra_sim_env` itself is never directly settable.
pub const ENVIRONMENT_LABEL: &str = "environment";

/// Labels marking the simulation, or carrying identity the runtime depends on.
/// Never settable or removable through user label surfaces.
const RESERVED_KEYS: &[&str] = &[
    "simulated",
    "infra_sim_name",
    "infra_sim_role",
    "infra_sim_env",
    "latitude",
    "longitude",
    "device_vendor",
    "device_model",
    "device_type",
];

/// Key-name fragments that mark a key as a credential. A label is published
/// metadata; none of these belongs in one.
const CREDENTIAL_FRAGMENTS: &[&str] = &[
    "token",
    "secret",
    "password",
    "passwd",
    "api_key",
    "apikey",
    "access_key",
    "private_key",
    "bearer",
    "credential",
];

/// Whether a key belongs to this project's generated label set (or the
/// agent's `_` namespace) rather than the user's.
pub fn is_generated_key(key: &str) -> bool {
    key.starts_with('_') || RESERVED_KEYS.contains(&key)
}

/// Validate one label key for a user-authored label.
///
/// Accepts exactly the keys the agent stores unchanged: `[A-Za-z0-9_.\-/]`,
/// non-empty, not all underscores, within the length cap. Everything else —
/// spaces, `:` (the agent turns it into `_`), UTF-8, control characters — is
/// refused with the reason, because each of those means the stored key would
/// differ from the authored one.
pub fn validate_key(key: &str) -> Result<(), String> {
    if key.is_empty() {
        return Err("a label key cannot be empty".into());
    }
    if let Some(pos) = key.chars().position(|c| !is_stable_key_char(c)) {
        let c = key.chars().nth(pos).unwrap();
        return Err(format!(
            "label key '{key}' contains '{c}' at position {pos}: the agent rewrites it, so the \
             node would show a different key than the one authored. Use [A-Za-z0-9_.-/]"
        ));
    }
    if key.chars().count() > MAX_KEY_LEN {
        return Err(format!(
            "label key '{key}' is longer than {MAX_KEY_LEN} characters"
        ));
    }
    if key.chars().all(|c| c == '_') {
        return Err(format!(
            "label key '{key}' is only underscores; the agent rejects that as a name"
        ));
    }
    if is_generated_key(key) {
        return Err(format!(
            "label key '{key}' is generated by the simulation itself and cannot be set by hand"
        ));
    }
    if let Some(f) = CREDENTIAL_FRAGMENTS
        .iter()
        .find(|f| key.to_lowercase().contains(*f))
    {
        return Err(format!(
            "label key '{key}' looks like a credential ('{f}'): labels are published metadata \
             and must never carry secrets"
        ));
    }
    Ok(())
}

/// Characters the agent stores in a key verbatim. From the sanitizer table:
/// letters, digits, `_ - . /` pass through; everything else (space, `: ; = ,
/// + @ ( )`, UTF-8, control) is rewritten to `_`, `.` or `/`.
fn is_stable_key_char(c: char) -> bool {
    c.is_ascii_alphanumeric() || matches!(c, '_' | '-' | '.' | '/')
}

/// Characters a value may carry without the agent rewriting them: letters,
/// digits, `_ - . / : @ ( ) +` and single interior spaces, plus UTF-8
/// (netdata/netdata @ c23face0bd94
/// `src/libnetdata/sanitizers/sanitizers-labels.c` value column). Everything
/// else ASCII - `! " # $ % & ' * < > ? ^ ` { | } ~` and friends - is rewritten
/// to `_` or space on arrival, and `; = , \` map to `: . /`; all are refused
/// here so the authored value is the stored value.
fn is_stable_value_char(c: char) -> bool {
    c.is_ascii_alphanumeric() || matches!(c, '_' | '-' | '.' | '/' | ':' | '@' | '(' | ')' | '+')
}

/// Validate one label value.
///
/// Accepts values the agent stores unchanged: no control characters, no
/// leading/trailing space, no doubled interior spaces, only stable characters
/// (see [`is_stable_value_char`]) or UTF-8, non-empty, within both value caps.
/// Interior single spaces and UTF-8 are fine — a site label of `Zürich
/// Hauptbahnhof` is legitimate.
pub fn validate_value(key: &str, value: &str) -> Result<(), String> {
    if value.is_empty() {
        return Err(format!(
            "label value for '{key}' is empty; an empty value renders as YAML null"
        ));
    }
    if value.chars().any(char::is_control) {
        return Err(format!(
            "label value for '{key}' contains a control character"
        ));
    }
    if value.starts_with(' ') || value.ends_with(' ') {
        return Err(format!(
            "label value for '{key}' has leading or trailing spaces, which the agent strips"
        ));
    }
    if value.contains("  ") {
        return Err(format!(
            "label value for '{key}' has doubled spaces, which the agent collapses"
        ));
    }
    if let Some(c) = value.chars().find(|c| !c.is_stable_value_char_or_utf8()) {
        return Err(format!(
            "label value for '{key}' contains '{c}', which the agent rewrites - use letters, \
             digits, UTF-8, or one of . - / : @ ( ) +"
        ));
    }
    let chars = value.chars().count();
    if chars > MAX_VALUE_CHARS {
        return Err(format!(
            "label value for '{key}' is {chars} characters; the cap is {MAX_VALUE_CHARS}"
        ));
    }
    if value.len() > MAX_VALUE_BYTES {
        return Err(format!(
            "label value for '{key}' is {} bytes; the cap is {MAX_VALUE_BYTES}",
            value.len()
        ));
    }
    Ok(())
}

trait StableValueChar {
    fn is_stable_value_char_or_utf8(&self) -> bool;
}

impl StableValueChar for char {
    fn is_stable_value_char_or_utf8(&self) -> bool {
        // A single interior space is stable; edge and doubled spaces are
        // already refused by the earlier checks.
        is_stable_value_char(*self) || *self == ' ' || *self >= '\u{0080}'
    }
}

/// Validate a key/value pair.
pub fn validate_pair(key: &str, value: &str) -> Result<(), String> {
    validate_key(key)?;
    validate_value(key, value)
}

/// Render a validated label value as a YAML scalar for `environment.yaml`.
///
/// Conservative by design: a value is emitted plain only when every character
/// is provably safe in a plain scalar's body AND at its start (no `: ` hazard,
/// no `#` comment start, no indicator characters, not typed-looking, not
/// empty). Everything else — values with spaces, `:`, UTF-8, leading digits
/// that YAML would type as numbers — is single-quoted. Validation refuses `'`
/// outright (the agent rewrites it), so a quoted scalar never needs escaping.
pub fn yaml_scalar(value: &str) -> String {
    let plain_safe = !value.is_empty()
        && value
            .chars()
            .next()
            .is_some_and(|c| c.is_ascii_alphanumeric() || c == '_')
        && value.chars().all(|c| {
            c.is_ascii_alphanumeric() || matches!(c, '_' | '-' | '.' | '@' | '(' | ')' | '/' | '+')
        })
        && !looks_typed(value);
    if plain_safe {
        value.to_string()
    } else {
        format!("'{value}'")
    }
}

/// Whether YAML would type a plain scalar as something other than a string
/// (`42`, `true`, `-1.5`, `~`), so it must be quoted to round-trip.
fn looks_typed(value: &str) -> bool {
    value.parse::<f64>().is_ok()
        || matches!(
            value.to_lowercase().as_str(),
            "true" | "false" | "null" | "yes" | "no" | "on" | "off" | "~"
        )
        || (value.starts_with('-')
            && value[1..]
                .chars()
                .next()
                .is_some_and(|c| c.is_ascii_digit()))
}

/// Validate a whole label map. Fails on the first problem, naming it.
pub fn validate_map(labels: &BTreeMap<String, String>) -> Result<(), String> {
    for (key, value) in labels {
        validate_pair(key, value)?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn map(pairs: &[(&str, &str)]) -> BTreeMap<String, String> {
        pairs
            .iter()
            .map(|(k, v)| (k.to_string(), v.to_string()))
            .collect()
    }

    #[test]
    fn accepts_keys_the_agent_stores_verbatim() {
        for key in [
            "team",
            "environment",
            "app.kubernetes.io/name",
            "dc-1",
            "service_layer/owner",
        ] {
            assert!(validate_key(key).is_ok(), "'{key}' should be stable");
        }
    }

    #[test]
    fn refuses_keys_the_agent_would_rewrite() {
        // Each of these is mutated by the agent's sanitizer; refusing them is
        // the difference between the authored file and the live node agreeing.
        for key in [
            "env prod", "env:prod", "env;prod", "env=prod", "env,prod", "env+prod", "env@x",
            "env(x)", "tüür",
        ] {
            assert!(validate_key(key).is_err(), "'{key}' should be refused");
        }
    }

    #[test]
    fn refuses_empty_and_underscore_only_keys() {
        assert!(validate_key("").is_err());
        assert!(validate_key("___").is_err());
    }

    #[test]
    fn refuses_overlong_keys() {
        let ok = "a".repeat(200);
        let long = "a".repeat(201);
        assert!(validate_key(&ok).is_ok());
        assert!(validate_key(&long).is_err());
    }

    #[test]
    fn closes_the_agent_and_simulation_namespaces() {
        for key in [
            "_os_name",
            "simulated",
            "infra_sim_name",
            "infra_sim_role",
            "infra_sim_env",
            "latitude",
            "longitude",
            "device_vendor",
        ] {
            assert!(validate_key(key).is_err(), "'{key}' is not user-settable");
            assert!(is_generated_key(key), "'{key}' must classify as generated");
        }
        assert!(!is_generated_key("team"), "team is a user key");
    }

    #[test]
    fn refuses_credential_looking_keys() {
        for key in ["api_key", "auth_token", "db_password", "bearer", "SECRET"] {
            assert!(
                validate_key(key).is_err(),
                "'{key}' looks like a credential"
            );
        }
        // Words that merely contain these letters are fine.
        for key in ["team", "keyboard", "monkey_business"] {
            assert!(validate_key(key).is_ok(), "'{key}' is not a credential");
        }
    }

    #[test]
    fn accepts_values_the_agent_stores_verbatim() {
        for value in [
            "production",
            "eu west 1",
            "Zürich Hauptbahnhof",
            "payments/checkout",
            "rack 12: primary",
            "a+b",
            "v1.2.3",
        ] {
            assert!(
                validate_value("site", value).is_ok(),
                "'{value}' should pass"
            );
        }
    }

    #[test]
    fn refuses_values_the_agent_would_rewrite() {
        // The agent's value map rewrites each of these (to `_` or space); the
        // old check covered spaces and `;=,\` only, and `AT&T` sailed through
        // to be stored as `AT_T` on the live node.
        for value in [
            " padded",
            "padded ",
            "double  space",
            "a;b",
            "a=b",
            "a,b",
            "a\\b",
        ] {
            assert!(
                validate_value("site", value).is_err(),
                "'{value}' should be refused"
            );
        }
        for bad in [
            '"', '\'', '#', '!', '$', '%', '&', '*', '<', '>', '?', '^', '`', '{', '|', '}', '~',
        ] {
            let value = format!("a{bad}b");
            assert!(
                validate_value("site", &value).is_err(),
                "'{value}' contains a char the agent rewrites"
            );
        }
    }

    #[test]
    fn refuses_empty_control_and_overlong_values() {
        assert!(
            validate_value("site", "").is_err(),
            "an empty value renders as YAML null"
        );
        assert!(validate_value("site", "bad\u{7}char").is_err());
        let ok = "a".repeat(MAX_VALUE_CHARS);
        let long = "a".repeat(MAX_VALUE_CHARS + 1);
        assert!(validate_value("site", &ok).is_ok());
        assert!(validate_value("site", &long).is_err());
        // 100 two-byte characters: within 200 chars, within 800 bytes.
        let utf8 = "ü".repeat(100);
        assert!(validate_value("site", &utf8).is_ok());
        // 500 two-byte characters: within the byte cap check ordering matters.
        let heavy = "ü".repeat(500);
        assert!(validate_value("site", &heavy).is_err());
    }

    #[test]
    fn yaml_scalar_quotes_everything_not_provably_plain() {
        // A plain scalar cannot carry `: `, start with an indicator, or be
        // typed-looking; anything else is single-quoted so the file always
        // round-trips as the string it was authored as.
        assert_eq!(yaml_scalar("dc-1"), "dc-1");
        assert_eq!(yaml_scalar("payments/checkout.v2"), "payments/checkout.v2");
        assert_eq!(yaml_scalar("42"), "'42'");
        assert_eq!(yaml_scalar("true"), "'true'");
        assert_eq!(yaml_scalar(""), "''");
        assert_eq!(yaml_scalar("rack 12: primary"), "'rack 12: primary'");
        assert_eq!(yaml_scalar("prod:us"), "'prod:us'");
        assert_eq!(yaml_scalar("Zürich"), "'Zürich'");
        assert_eq!(yaml_scalar("-x"), "'-x'");
        // Every form parses back as the exact string.
        for v in [
            "rack 12: primary",
            "42",
            "",
            "Zürich",
            "a: b #not-a-comment",
        ] {
            let rendered = format!("k: {}", yaml_scalar(v));
            let back: std::collections::BTreeMap<String, String> =
                serde_yaml::from_str(&rendered).unwrap();
            assert_eq!(back.get("k").map(String::as_str), Some(v), "{rendered}");
        }
    }

    #[test]
    fn a_valid_map_passes_and_names_its_first_problem() {
        assert!(validate_map(&map(&[("team", "payments"), ("site", "dc-1")])).is_ok());
        let err = validate_map(&map(&[("team", "payments"), ("site", "a,b")])).unwrap_err();
        assert!(err.contains("site"), "{err}");
    }
}
